POST http://localhost:5000/superadmin
Content-Type: application/json

{
    "name": "anibong",
    "email": "anibong@gmail.com",
    "password": "123",
    "confPassword": "123",
    "role": "superadmin"
}

###
GET http://localhost:5000/admin


###
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "ronalis@gmail.com",
    "password": "ronalis12"
}

###
GET http://localhost:5000/api/refreshtoken

###
DELETE http://localhost:5000/api/logout

###
GET http://localhost:5000/api/ibuhamil
Authorization: Bearer 


###
POST http://localhost:5000/anak
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJvcGV0IiwiZW1haWwiOiJvcGV0QGdtYWlsLmNvbSIsInVzZXJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODQ3NjI2ODIsImV4cCI6MTY4NDc2MjcwMn0.GliKDV4vvgkRdZjET_tIOnwQHxTB3v2W_Q3YovFnZ8U

{
    "nama": "monika",
    "ibuhamilId": "5"
}


###
POST http://localhost:5000/admin
Content-Type: application/json

{
    "name": "oyen",
    "email": "oyen@gmail.com",
    "password": "123",
    "confPassword": "123",
    "role": "admin"
}

###
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "ronalis@gmail.com",
    "password": "ronalis12"
}

###
GET http://localhost:5000/api/anak
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWEiOiJSb25hbGlzIiwiZW1haWwiOiJyb25hbGlzQGdtYWlsLmNvbSIsInVzZXJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODY1NDMzNTcsImV4cCI6MTY4NjU0MzM4N30.UQSOGKYo5pxduj4E4iIqs5bVwy_skCGOYwsotfigyQQ


###
DELETE http://localhost:5000/api/ibuhamil/9f808eec-5fbe-4115-ba59-f1690c4422ef
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJyb25hbGlzIiwiZW1haWwiOiJyb25hbGlzQGdtYWlsLmNvbSIsInVzZXJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODY0ODMyMDIsImV4cCI6MTY4NjQ4MzIzMn0.ZEQL0naL93ty0E0UgTmyQUaQrOATcgjO2FVIEvDpyZQ

###
GET http://localhost:5000/nifas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm5hbWUiOiJSb25hbGlzIiwiZW1haWwiOiJyb25hbGlzQGdtYWlsLmNvbSIsInVzZXJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODYwMzU4NDksImV4cCI6MTY4NjAzNTg2OX0.EtFMIrck9K0U8Tmar--JrcuTpdADCQBZgicKG3CgmuQ

###
POST http://localhost:5000/anak
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJyb25hbCIsImVtYWlsIjoicm9uYWxAZ21haWwuY29tIiwiaWF0IjoxNjg0NzU0ODI1LCJleHAiOjE2ODQ3NTQ4NDV9.9WpT-F0fIRqvMcnjuLzqTXD15fexQJ3ZEAnUWDOPsbc

{
    "name": "Fifin zaitun"
}

###
GET http://localhost:5000/ibuhamil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJveWVuIiwiZW1haWwiOiJveWVuQGdtYWlsLmNvbSIsInVzZXJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODU4ODYwMDUsImV4cCI6MTY4NTg4NjAyMH0.b2VsMnhgKGBziwLKoM-IffjvYoT34x6oO_ZsWBI4RYU

###
PATCH http://localhost:5000/api/ibuhamil/78
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIyLCJuYW1lIjoiUm9uYWxpcyIsImVtYWlsIjoicm9uYWxpc0BnbWFpbC5jb20iLCJ1c2Vycm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2MjM4MTY3LCJleHAiOjE2ODYyMzgxOTd9.bux5kdmZmNP0mDKKPv5aLQ3fMGUPU7SssWwOvtU3rMQ

{
    "name": "Samuel updated",
    "umur": "21",
    "lama_nikah": "10",
    "suku": "makassar",
    "agama": "islam",
    "pendidikan": "sarjana ekonomi",
    "pekerjaan": "dosen",
    "alamat": "makassar",
    "nomor_telefon": "082188079182",
    "golongan_darah": "B",
    "nomor_bpjs": "1234567890",
    "tempat_pemeriksaan": "pustu",
    "nama_suami": "atan",
    "umur_suami": "21",
    "agama_suami": "islam",
    "suku_suami": "makassar",
    "pendidikan_suami": "sarjana ekonomi",
    "pekerjaan_suami": "dosen",
    "alamat_suami": "makassar",
    "nomortelefon_suami": "082188079182",
    "email": "anibong@gmail.com",
    "password": "anibong12",
    "role": "pasien"
}

###
GET http://localhost:5000/ibuhamil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJvZmluIiwiZW1haWwiOiJvZmluQGdtYWlsLmNvbSIsInVzZXJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODQ3NTc3NTIsImV4cCI6MTY4NDc1Nzc3Mn0.gniPrHVmSePR8VgJdfnTdQpZpNtway0LrDXILarv8S0

###
GET http://localhost:5000/nifas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm5hbWUiOiJSb25hbGlzIiwiZW1haWwiOiJyb25hbGlzQGdtYWlsLmNvbSIsInVzZXJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODUyNzEyMzQsImV4cCI6MTY4NTI3MTI0NH0.yyE2mg1AaN-T7nArWZHdW9cKFf6yHef94jvdLf8DNLs