POST http://localhost:5000/api/superadmin
Content-Type: application/json

{
    "name": "Ronalis",
    "email": "ronalissaputra@gmail.com",
    "password": "ronalissaputra12",
    "confPassword": "ronalissaputra12",
    "role": "superadmin"
}

###
GET http://localhost:5000/admin


###
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "jhon@gmail.com",
    "password": "jhon12"
}

###
GET http://localhost:5000/api/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWEiOiJqaG9uIiwiZW1haWwiOiJqaG9uQGdtYWlsLmNvbSIsInVzZXJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODY1NjQxNzMsImV4cCI6MTY4NjU2NDIwM30.QP_3JlUMgCvKdXMcpxAEE36Wd706ZDSCtqsxAXHyGAE

###
DELETE http://localhost:5000/api/logout

###
GET http://localhost:5000/api/ibuhamil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoicm9uYWxpc3NhcHV0cmFAZ21haWwuY29tIiwidXNlcnJvbGUiOiJzdXBlcmFkbWluIiwiaWF0IjoxNjg2NTYxNDM4LCJleHAiOjE2ODY1NjE0Njh9.DhgleWMizS0Srqjc3KYuNSIUa1gbJqXmSIwzOrce3CE


###
POST http://localhost:5000/anak
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJvcGV0IiwiZW1haWwiOiJvcGV0QGdtYWlsLmNvbSIsInVzZXJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODQ3NjI2ODIsImV4cCI6MTY4NDc2MjcwMn0.GliKDV4vvgkRdZjET_tIOnwQHxTB3v2W_Q3YovFnZ8U

{
    "nama": "monika",
    "ibuhamilId": "5"
}


###
POST http://localhost:5000/admin
Content-Type: application/json

{
    "name": "oyen",
    "email": "oyen@gmail.com",
    "password": "123",
    "confPassword": "123",
    "role": "admin"
}

###
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "ronalis@gmail.com",
    "password": "ronalis12"
}

###
GET http://localhost:5000/api/pemantauankehamilan
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWEiOiJSb25hbGlzIiwiZW1haWwiOiJyb25hbGlzQGdtYWlsLmNvbSIsInVzZXJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODY2NjMxNTQsImV4cCI6MTY4NjY2MzE4NH0.1n-gdTKNHBbPC6pf7nTDt76w7FGgK7CpF1S3LDoPZb8


###
DELETE http://localhost:5000/api/ibuhamil/9f808eec-5fbe-4115-ba59-f1690c4422ef
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJyb25hbGlzIiwiZW1haWwiOiJyb25hbGlzQGdtYWlsLmNvbSIsInVzZXJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODY0ODMyMDIsImV4cCI6MTY4NjQ4MzIzMn0.ZEQL0naL93ty0E0UgTmyQUaQrOATcgjO2FVIEvDpyZQ

###
GET http://localhost:5000/nifas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm5hbWUiOiJSb25hbGlzIiwiZW1haWwiOiJyb25hbGlzQGdtYWlsLmNvbSIsInVzZXJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODYwMzU4NDksImV4cCI6MTY4NjAzNTg2OX0.EtFMIrck9K0U8Tmar--JrcuTpdADCQBZgicKG3CgmuQ

###
POST http://localhost:5000/anak
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJyb25hbCIsImVtYWlsIjoicm9uYWxAZ21haWwuY29tIiwiaWF0IjoxNjg0NzU0ODI1LCJleHAiOjE2ODQ3NTQ4NDV9.9WpT-F0fIRqvMcnjuLzqTXD15fexQJ3ZEAnUWDOPsbc

{
    "name": "Fifin zaitun"
}

###
GET http://localhost:5000/api/ibuhamil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWEiOiJqaG9uIiwiZW1haWwiOiJqaG9uQGdtYWlsLmNvbSIsInVzZXJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODY1NzYwMDUsImV4cCI6MTY4NjU3NjAzNX0.Qh07t9Hvcrfx9AIMFhUUCGJ5E556N5bKq8qyuc_rgD0

###
PATCH http://localhost:5000/api/ibuhamil/2636d7bd-2a02-499f-bd8d-e9a3b98d56c6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWEiOiJqaG9uIiwiZW1haWwiOiJqaG9uQGdtYWlsLmNvbSIsInVzZXJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODY2NTU3NDksImV4cCI6MTY4NjY1NTc3OX0.EoDoM8TPOi6t041I6w5-cPMVp9Zb5BHC-8VqPiDX2nw

{
    "nama": "asna updated",
    "umur": "sa",
    "lama_nikah": "sa",
    "suku": "as",
    "agama": "sas",
    "pendidikan": "as",
    "pekerjaan": "fdg",
    "alamat": "dfg",
    "nomor_hp": "dfd",
    "golongan_darah": "fgd",
      "nomor_bpjs": "fg",
      "tempat_periksa": "dfg",
      "nama_suami": "dfg",
      "umur_suami": "sdf",
      "agama_suami": "dfg",
      "suku_suami": "dfg",
      "pendidikan_suami": "dfg",
      "pekerjaan_suami": "dfg",
      "alamat_suami": "dfg",
      "nomorhp_suami": "dfg",
      "hamil_ke": "dfg",
      "jumlah_anak": "dfg",
      "siklus": "dfg",
      "lama_haid": "dfg",
      "hptp": "dfg",
      "hpl": "dfg",
      "email": "asna@gmail.com",
      "password": "asna123",
      "role": "pasien"
}

###
GET http://localhost:5000/ibuhamil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJvZmluIiwiZW1haWwiOiJvZmluQGdtYWlsLmNvbSIsInVzZXJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODQ3NTc3NTIsImV4cCI6MTY4NDc1Nzc3Mn0.gniPrHVmSePR8VgJdfnTdQpZpNtway0LrDXILarv8S0

###
GET http://localhost:5000/nifas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm5hbWUiOiJSb25hbGlzIiwiZW1haWwiOiJyb25hbGlzQGdtYWlsLmNvbSIsInVzZXJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODUyNzEyMzQsImV4cCI6MTY4NTI3MTI0NH0.yyE2mg1AaN-T7nArWZHdW9cKFf6yHef94jvdLf8DNLs